# Kubernetes declaration of Identifiers.org Metadata Resolution API Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: v1
kind: Service
metadata:
    name: nodeport-metadata
    namespace: idorg-satellite
    #annotations:
    #    cloud.google.com/neg: '{"ingress": true}'
    labels:
        environment: production
        tier: api
        app: metadata
        deployment: satellite
spec:
    ports:
    - port: 8082
    selector:
        environment: production
        tier: api
        app: metadata
        deployment: satellite
    type: NodePort
