# Definition of Redis backend service for Identifiers.org
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: v1
kind: Service
metadata:
    name: redis
    namespace: idorg-satellite
    labels:
        environment: production
        tier: backend
        app: redis
        deployment: satellite
spec:
    ports:
    - port: 6379
    selector:
        environment: production
        tier: backend
        app: redis
        deployment: satellite
